parthiban/w2s_project/manager/urls.py
from django.urls import path, include
from . import views
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import views as auth_views
from .forms import UserPasswordResetForm,PasswordResetConfirmViewForm,passwordchangingform

urlpatterns = [     
    path('login/', views.login_1, name='auth_login'),
    path('logout/', views.logout_1, name='auth_logout'),
    path('reset-password/',auth_views.PasswordResetView.as_view(template_name='reset_password/password_reset.html',form_class=UserPasswordResetForm),name = "reset_password"),
    path('reset-password-sent/',auth_views.PasswordResetDoneView.as_view(template_name='reset_password/password-reset-sent.html'),name ="password_reset_done"),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='reset_password/password-reset-confirm.html',form_class=PasswordResetConfirmViewForm),name = "password_reset_confirm"),
    path('reset-password/',auth_views.PasswordResetCompleteView.as_view(template_name='reset_password/password-complete.html'),name = "password_reset_complete"),
    path('change_password/',views.change_password, name='change_password'),
    path('Dashboard/', views.home, name='home'),
]

parthiban/w2s_project/w2s_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('manager.urls')),
    path('employee/',include('employee.urls')),


]
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

parthiban/w2s_project/manager/forms.py
from .models import *
from django import forms
from django.contrib.auth.forms import *
from django.contrib.auth.models import User

class passwordchangingform(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control','type':'password','id':"password1","autocomplete":"current-password"}))
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={"autocomplete":"new-password",'class': 'form-control','type':'password','id':"password2","style":"position:relative;"}))
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control','type':'password','id':"password3"}))
    class meta:
        model = User
        fields = ('old_password','new_password1','new_password2')

class UserPasswordResetForm(PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super(UserPasswordResetForm, self).__init__(*args, **kwargs)

    email = forms.EmailField(label='', widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'placeholder': 'EMail ID',
        'type': 'email',
        'name': 'email'
        }))

class PasswordResetConfirmViewForm(SetPasswordForm):

    def __init__(self, *args, **kwargs):
        super(PasswordResetConfirmViewForm, self).__init__(*args, **kwargs)
    new_password1 = forms.CharField(label='', widget=forms.TextInput(attrs={
    'class': 'form-control',
    'placeholder': 'Password',
    'type': 'password',
    'name': 'new_password1'
    }))
    new_password2 = forms.CharField(label='', widget=forms.TextInput(attrs={
    'class': 'form-control',
    'placeholder': 'Confirm Password',
    'type': 'password',
    'name': 'new_password1'
    }))

parthiban/w2s_project/templates/reset_password/password-complete.html
{% load static %}
<!doctype html>
<html class="no-js" lang="">


<!-- Mirrored from affixtheme.com/html/xmee/demo/register-9.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 18 Aug 2021 09:28:16 GMT -->
<head>
	<meta charset="utf-8">
	<meta http-equiv="x-ua-compatible" content="ie=edge">
	<title>W2S</title>
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- Favicon -->
	<link rel="shortcut icon" type="image/x-icon" href="{% static '/img/favicon.png' %}">
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="{% static 'login/css/bootstrap.min.css' %}">
	<!-- Fontawesome CSS -->
	<link rel="stylesheet" href="{% static 'login/css/fontawesome-all.min.css' %}">
	<!-- Flaticon CSS -->
	<link rel="stylesheet" href="{% static 'login/font/flaticon.css' %}">
	<!-- Google Web Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&amp;display=swap" rel="stylesheet">
	<!-- Custom CSS -->
	<link rel="stylesheet" href="{% static 'login/style.css' %}">

</head>
<body>
	<!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
	<section class="fxt-template-animation fxt-template-layout9" data-bg-image="http://mayagreens.net/static/login/img/figure/bg9-l.jpg">
		<div class="container">
			<div class="row align-items-center justify-content-center">
				<div class="col-lg-3 col-12">
					<div class="fxt-header">
						<a href="https://mayagreens.net/" class="fxt-logo"><img src="http://mayagreens.net/static/logo.png" alt="Logo"></a>
					</div>
				</div>
				<div class="col-lg-6 col-12">
					<div class="fxt-content">
						<h2>you password hasbeen complete</h2>
						<!-- <div class="fxt-form">
							<form class="login100-form validate-form" action="/login/" method="POST">
								{% csrf_token %}
								<div class="form-group">
									<div class="fxt-transformY-50 fxt-transition-delay-1">
										<input type="text" id="name" class="form-control" name="log_emp_id" placeholder="User ID" required="required">
									</div>
								</div>
								<div class="form-group">
									<div class="fxt-transformY-50 fxt-transition-delay-2">
										<input id="password" type="password" class="form-control" name="log_password" placeholder="********" required="required">
										<i toggle="#password" class="fa fa-fw fa-eye toggle-password field-icon"></i>
									</div>
								</div>
                                {{form}}
								 <div class="form-group">
									<div class="fxt-transformY-50 fxt-transition-delay-3">
										<div class="fxt-checkbox-area">
											<div class="checkbox">
												<input id="checkbox1" type="checkbox">
												<label for="checkbox1">Keep me logged in</label>
											</div>
											<a href="{% url 'reset_password" class="switcher-text">Forgot Password</a>

										</div>
									</div>
								</div> 
							
                                <div class="form-group">
									<div class="fxt-transformY-50 fxt-transition-delay-4">
										<button type="submit" class="fxt-btn-fill">Login</button>
									</div>
								</div>
							</form>
						</div> -->
						
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- jquery-->
	<script src="{% static 'login/js/jquery-3.5.0.min.js' %}"></script>
	<!-- Popper js -->
	<script src="{% static 'login/js/login/js/popper.min.js' %}"></script>
	<!-- Bootstrap js -->
	<script src="{% static 'login/js/js/bootstrap.min.js' %}"></script>
	<!-- Imagesloaded js -->
	<script src="{% static 'login/js/imagesloaded.pkgd.min.js' %}"></script>
	<!-- Validator js -->
	<script src="{% static 'login/js/validator.min.js' %}"></script>
	<!-- Custom Js -->
	<script src="{% static 'login/js/main.js' %}"></script>

</body>


<!-- Mirrored from affixtheme.com/html/xmee/demo/register-9.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 18 Aug 2021 09:28:16 GMT -->
</html>

parthiban/w2s_project/templates/reset_password/password-reset-confirm.html
{% load static %}
<!doctype html>
<html class="no-js" lang="">


<!-- Mirrored from affixtheme.com/html/xmee/demo/register-9.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 18 Aug 2021 09:28:16 GMT -->
<head>
	<meta charset="utf-8">{% load static %}
    <!doctype html>
    <html class="no-js" lang="">
    
    
    <!-- Mirrored from affixtheme.com/html/xmee/demo/register-9.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 18 Aug 2021 09:28:16 GMT -->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>W2S</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Favicon -->
        <link rel="shortcut icon" type="image/x-icon" href="http://mayagreens.net/staticlogin/img/favicon.png">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="http://mayagreens.net/static/login/css/bootstrap.min.css">
        <!-- Fontawesome CSS -->
        <link rel="stylesheet" href="http://mayagreens.net/static/login/css/fontawesome-all.min.css">
        <!-- Flaticon CSS -->
        <link rel="stylesheet" href="http://mayagreens.net/static/login/font/flaticon.css">
        <!-- Google Web Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&amp;display=swap" rel="stylesheet">
        <!-- Custom CSS -->
        <link rel="stylesheet" href="http://mayagreens.net/static/login/style.css">
    </head>
    
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <section class="fxt-template-animation fxt-template-layout9" data-bg-image="{% static 'login/img/figure/bg9-l.jpg' %}">
            <div class="container">
                <div class="row align-items-center justify-content-center">
                    
                    <div class="col-lg-6 col-12">
                        <div class="fxt-content">
                            <h2>Change Password</h2>
                            <div class="fxt-form">
                                <form class="login100-form validate-form" method="POST" >
                                    {% csrf_token %}
                                    <div class="form-group">
                                        {{form.new_password1}}
                                        <div class="fxt-transformY-50 fxt-transition-delay-2">
                                            <i toggle="#id_new_password1" class="fa fa-fw fa-eye toggle-password field-icon"></i>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="fxt-transformY-50 fxt-transition-delay-2">
                                            {{form.new_password2}}
                                            <i toggle="#id_new_password2" class="fa fa-fw fa-eye toggle-password field-icon"></i>
                                        </div>
                                    </div>
                                    {% if form.errors %}
                                        <div class="alert alert-danger">
                                            <strong>{{form.errors}}</strong> 
                                        </div>
                                    {% endif %}
                                    
                                    
                                    <div class="form-group">
                                        <div class="fxt-transformY-50 fxt-transition-delay-4">
                                            <button type="submit" class="fxt-btn-fill">Send</button>
                                        </div>
                                    </div>
                                    <div class="fxt-footer">
                                        <div class="fxt-transformY-50 fxt-transition-delay-9">
                                            <p>Already have an account?<a href="{% url 'auth_login' %}" class="switcher-text2 inline-text">Log in</a></p>
                                        </div>
                                    </div>
                                </form>
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- jquery-->
        <script src="http://mayagreens.net/static/login/js/jquery-3.5.0.min.js"></script>
        <!-- Popper js -->
        <script src="http://mayagreens.net/static/login/js/popper.min.js"></script>
        <!-- Bootstrap js -->
        <script src="http://mayagreens.net/static/login/js/bootstrap.min.js"></script>
        <!-- Imagesloaded js -->
        <script src="http://mayagreens.net/static/login/js/imagesloaded.pkgd.min.js"></script>
        <!-- Validator js -->
        <script src="http://mayagreens.net/static/login/js/validator.min.js"></script>
        <!-- Custom Js -->
        <script src="http://mayagreens.net/static/login/js/main.js"></script>
    
    </body>
    
    
    <!-- Mirrored from affixtheme.com/html/xmee/demo/register-9.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 18 Aug 2021 09:28:16 GMT -->
    </html>
	


parthiban/w2s_project/templates/reset_password/password-reset-sent.html
{% load static %}
<!doctype html>
<html class="no-js" lang="">


<!-- Mirrored from affixtheme.com/html/xmee/demo/register-9.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 18 Aug 2021 09:28:16 GMT -->
<head>
	<meta charset="utf-8">
	<meta http-equiv="x-ua-compatible" content="ie=edge">
	<title>W2S</title>
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- Favicon -->
	<link rel="shortcut icon" type="image/x-icon" href="{% static '/img/favicon.png' %}">
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="{% static 'login/css/bootstrap.min.css' %}">
	<!-- Fontawesome CSS -->
	<link rel="stylesheet" href="{% static 'login/css/fontawesome-all.min.css' %}">
	<!-- Flaticon CSS -->
	<link rel="stylesheet" href="{% static 'login/font/flaticon.css' %}">
	<!-- Google Web Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&amp;display=swap" rel="stylesheet">
	<!-- Custom CSS -->
	<link rel="stylesheet" href="{% static 'login/style.css' %}">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>

<body>
	<!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
	<section class="fxt-template-animation fxt-template-layout9" data-bg-image="{% static 'login/img/figure/bg9-l.jpg' %}">
		<div class="container">
			<div class="row align-items-center justify-content-center">
				
				<div class="col-lg-6 col-12">
					<div class="fxt-content">
						<h2>Mail Sended</h2>
						<div class="fxt-form">
							<div class="alert alert-danger">
								<strong>
									We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.

									If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.
								</strong> 
							</div>
							
						</div>
						<div class="fxt-footer">
							<div class="fxt-transformY-50 fxt-transition-delay-9">
								<p>Already have an account?<a href="{% url 'auth_login' %}" class="switcher-text2 inline-text">Log in</a></p>
							</div>
						</div>
						
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- jquery-->
	<script src="{% static 'login/js/jquery-3.5.0.min.js' %}"></script>
	<!-- Popper js -->
	<script src="{% static 'login/js/login/js/popper.min.js' %}"></script>
	<!-- Bootstrap js -->
	<script src="{% static 'login/js/js/bootstrap.min.js' %}"></script>
	<!-- Imagesloaded js -->
	<script src="{% static 'login/js/imagesloaded.pkgd.min.js' %}"></script>
	<!-- Validator js -->
	<script src="{% static 'login/js/validator.min.js' %}"></script>
	<!-- Custom Js -->
	<script src="{% static 'login/js/main.js' %}"></script>

</body>


<!-- Mirrored from affixtheme.com/html/xmee/demo/register-9.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 18 Aug 2021 09:28:16 GMT -->
</html>

parthiban/w2s_project/templates/reset_password/password_reset.html
{% load static %}
<!doctype html>
<html class="no-js" lang="">


<!-- Mirrored from affixtheme.com/html/xmee/demo/register-9.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 18 Aug 2021 09:28:16 GMT -->
<head>
	<meta charset="utf-8">
	<meta http-equiv="x-ua-compatible" content="ie=edge">
	<title>W2s</title>
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- Favicon -->
	<link rel="shortcut icon" type="image/x-icon" href="{% static '/img/favicon.png' %}">
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="{% static 'login/css/bootstrap.min.css' %}">
	<!-- Fontawesome CSS -->
	<link rel="stylesheet" href="{% static 'login/css/fontawesome-all.min.css' %}">
	<!-- Flaticon CSS -->
	<link rel="stylesheet" href="{% static 'login/font/flaticon.css' %}">
	<!-- Google Web Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&amp;display=swap" rel="stylesheet">
	<!-- Custom CSS -->
	<link rel="stylesheet" href="{% static 'login/style.css' %}">

</head>

<body>
	<!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
	<section class="fxt-template-animation fxt-template-layout9" data-bg-image="{% static 'login/img/figure/bg9-l.jpg' %}">
		<div class="container">
			<div class="row align-items-center justify-content-center">
				
				<div class="col-lg-6 col-12">
					<div class="fxt-content">
						<h2>Send Mail</h2>
						<div class="fxt-form">
							<form class="login100-form validate-form" method="POST">
								{% csrf_token %}
								<div class="form-group">
									<div class="fxt-transformY-50 fxt-transition-delay-1">
                                        {{form.email}}
										<!-- <input type="text" id="name" class="form-control" name="log_emp_id" placeholder="User ID" required="required"> -->
									</div>
								</div>
								
								
								<div class="form-group">
									<div class="fxt-transformY-50 fxt-transition-delay-4">
										<button type="submit" class="fxt-btn-fill">Send</button>
									</div>
								</div>
								<div class="fxt-footer">
									<div class="fxt-transformY-50 fxt-transition-delay-9">
										<p>Already have an account?<a href="{% url 'auth_login' %}" class="switcher-text2 inline-text">Log in</a></p>
									</div>
								</div>
							</form>
						</div>
						
					</div>
				</div>
			</div>
		</div>
	</section>
	<script src="{% static 'login/js/jquery-3.5.0.min.js' %}"></script>
	<!-- Popper js -->
	<script src="{% static 'login/js/login/js/popper.min.js' %}"></script>
	<!-- Bootstrap js -->
	<script src="{% static 'login/js/js/bootstrap.min.js' %}"></script>
	<!-- Imagesloaded js -->
	<script src="{% static 'login/js/imagesloaded.pkgd.min.js' %}"></script>
	<!-- Validator js -->
	<script src="{% static 'login/js/validator.min.js' %}"></script>
	<!-- Custom Js -->
	<script src="{% static 'login/js/main.js' %}"></script>

</body>


<!-- Mirrored from affixtheme.com/html/xmee/demo/register-9.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 18 Aug 2021 09:28:16 GMT -->
</html>